/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as pagePageRouteImport } from './routes/(page)/_page'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as pagePageUsersRouteImport } from './routes/(page)/_page.users'
import { Route as pagePageProfileRouteImport } from './routes/(page)/_page.profile'
import { Route as pagePageMenusRouteImport } from './routes/(page)/_page.menus'
import { Route as pagePageDashboardRouteImport } from './routes/(page)/_page.dashboard'
import { Route as pagePageCodesRouteImport } from './routes/(page)/_page.codes'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/_auth.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const pagePageRoute = pagePageRouteImport.update({
  id: '/(page)/_page',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const pagePageUsersRoute = pagePageUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => pagePageRoute,
} as any)
const pagePageProfileRoute = pagePageProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => pagePageRoute,
} as any)
const pagePageMenusRoute = pagePageMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => pagePageRoute,
} as any)
const pagePageDashboardRoute = pagePageDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => pagePageRoute,
} as any)
const pagePageCodesRoute = pagePageCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => pagePageRoute,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authAuthLoginRoute
  '/codes': typeof pagePageCodesRoute
  '/dashboard': typeof pagePageDashboardRoute
  '/menus': typeof pagePageMenusRoute
  '/profile': typeof pagePageProfileRoute
  '/users': typeof pagePageUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authAuthLoginRoute
  '/codes': typeof pagePageCodesRoute
  '/dashboard': typeof pagePageDashboardRoute
  '/menus': typeof pagePageMenusRoute
  '/profile': typeof pagePageProfileRoute
  '/users': typeof pagePageUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(page)/_page': typeof pagePageRouteWithChildren
  '/(auth)/_auth/login': typeof authAuthLoginRoute
  '/(page)/_page/codes': typeof pagePageCodesRoute
  '/(page)/_page/dashboard': typeof pagePageDashboardRoute
  '/(page)/_page/menus': typeof pagePageMenusRoute
  '/(page)/_page/profile': typeof pagePageProfileRoute
  '/(page)/_page/users': typeof pagePageUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/codes'
    | '/dashboard'
    | '/menus'
    | '/profile'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/codes'
    | '/dashboard'
    | '/menus'
    | '/profile'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/(auth)/_auth'
    | '/(page)/_page'
    | '/(auth)/_auth/login'
    | '/(page)/_page/codes'
    | '/(page)/_page/dashboard'
    | '/(page)/_page/menus'
    | '/(page)/_page/profile'
    | '/(page)/_page/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authAuthRoute: typeof authAuthRouteWithChildren
  pagePageRoute: typeof pagePageRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(page)/_page': {
      id: '/(page)/_page'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof pagePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(page)/_page/users': {
      id: '/(page)/_page/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof pagePageUsersRouteImport
      parentRoute: typeof pagePageRoute
    }
    '/(page)/_page/profile': {
      id: '/(page)/_page/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof pagePageProfileRouteImport
      parentRoute: typeof pagePageRoute
    }
    '/(page)/_page/menus': {
      id: '/(page)/_page/menus'
      path: '/menus'
      fullPath: '/menus'
      preLoaderRoute: typeof pagePageMenusRouteImport
      parentRoute: typeof pagePageRoute
    }
    '/(page)/_page/dashboard': {
      id: '/(page)/_page/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof pagePageDashboardRouteImport
      parentRoute: typeof pagePageRoute
    }
    '/(page)/_page/codes': {
      id: '/(page)/_page/codes'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof pagePageCodesRouteImport
      parentRoute: typeof pagePageRoute
    }
    '/(auth)/_auth/login': {
      id: '/(auth)/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
  }
}

interface authAuthRouteChildren {
  authAuthLoginRoute: typeof authAuthLoginRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthLoginRoute: authAuthLoginRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

interface pagePageRouteChildren {
  pagePageCodesRoute: typeof pagePageCodesRoute
  pagePageDashboardRoute: typeof pagePageDashboardRoute
  pagePageMenusRoute: typeof pagePageMenusRoute
  pagePageProfileRoute: typeof pagePageProfileRoute
  pagePageUsersRoute: typeof pagePageUsersRoute
}

const pagePageRouteChildren: pagePageRouteChildren = {
  pagePageCodesRoute: pagePageCodesRoute,
  pagePageDashboardRoute: pagePageDashboardRoute,
  pagePageMenusRoute: pagePageMenusRoute,
  pagePageProfileRoute: pagePageProfileRoute,
  pagePageUsersRoute: pagePageUsersRoute,
}

const pagePageRouteWithChildren = pagePageRoute._addFileChildren(
  pagePageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authAuthRoute: authAuthRouteWithChildren,
  pagePageRoute: pagePageRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
