/**
 * This file was auto-generated by scripts/gen-api.mjs.
 * Do not make direct changes to the file.
 */

export type { auth } from './auth.schema';
export type { product } from './product.schema';
