/**
 * This file was auto-generated by openapi-typescript (via scripts/gen-api.mjs).
 * Do not make direct changes to the file.
 */

export namespace product {
  export interface paths {
      "/list": {
          parameters: {
              query?: never;
              header?: never;
              path?: never;
              cookie?: never;
          };
          get?: never;
          put?: never;
          /**
           * 상품 목록 조회
           * @description 조건에 맞는 상품 목록을 조회한다.
           */
          post: operations["getProductList"];
          delete?: never;
          options?: never;
          head?: never;
          patch?: never;
          trace?: never;
      };
      "/detail/{productId}": {
          parameters: {
              query?: never;
              header?: never;
              path?: never;
              cookie?: never;
          };
          get?: never;
          put?: never;
          /**
           * 상품 단건 조회
           * @description 상품 ID로 단건 상품을 조회한다.
           */
          post: operations["getProduct"];
          delete?: never;
          options?: never;
          head?: never;
          patch?: never;
          trace?: never;
      };
  }
  export type webhooks = Record<string, never>;
  export interface components {
      schemas: {
          ProductListResponse: {
              /**
               * Format: int64
               * @description 상품 ID
               * @example 1001
               */
              productId: number;
              /**
               * @description 상품명
               * @example 안정형 펀드
               */
              productNm: string;
              /**
               * Format: int64
               * @description 가격
               * @example 100000
               */
              price?: number;
          };
          ProductDetailResponse: {
              /**
               * Format: int64
               * @description 상품 ID
               * @example 1001
               */
              productId: number;
              /**
               * @description 상품명
               * @example 안정형 펀드
               */
              productNm: string;
              /** @description 상품 설명 */
              productDesc: string;
              /**
               * Format: int64
               * @description 가격
               * @example 100000
               */
              price: number;
              /**
               * Format: int32
               * @description 재고 수량
               * @example 50
               */
              stockQty: number;
              /**
               * @description 사용 여부 (Y/N)
               * @example Y
               * @enum {string}
               */
              useYn?: "Y" | "N";
          };
          ProductListRequest: {
              /**
               * @description 상품명
               * @example 안정형 펀드
               */
              productNm?: string;
              /**
               * @description 사용 여부 (Y/N)
               * @example Y
               * @enum {string}
               */
              useYn?: "Y" | "N";
          };
      };
      responses: never;
      parameters: never;
      requestBodies: never;
      headers: never;
      pathItems: never;
  }
  export type $defs = Record<string, never>;
  export interface operations {
      getProductList: {
          parameters: {
              query?: never;
              header?: never;
              path?: never;
              cookie?: never;
          };
          requestBody: {
              content: {
                  "application/json": components["schemas"]["ProductListRequest"];
              };
          };
          responses: {
              /** @description OK */
              200: {
                  headers: {
                      [name: string]: unknown;
                  };
                  content: {
                      "*/*": {
                          /** @description 성공 여부 */
                          success?: boolean;
                          /** @description 응답 코드 */
                          code?: string;
                          /** @description 응답 메시지 */
                          msg?: string;
                          /** @description 요청 추적 ID */
                          requestId?: string;
                          payload?: components["schemas"]["ProductListResponse"][];
                      };
                  };
              };
          };
      };
      getProduct: {
          parameters: {
              query?: never;
              header?: never;
              path: {
                  /**
                   * @description 상품 ID
                   * @example 1001
                   */
                  productId: number;
              };
              cookie?: never;
          };
          requestBody?: never;
          responses: {
              /** @description OK */
              200: {
                  headers: {
                      [name: string]: unknown;
                  };
                  content: {
                      "*/*": {
                          /** @description 성공 여부 */
                          success?: boolean;
                          /** @description 응답 코드 */
                          code?: string;
                          /** @description 응답 메시지 */
                          msg?: string;
                          /** @description 요청 추적 ID */
                          requestId?: string;
                          payload?: components["schemas"]["ProductDetailResponse"];
                      };
                  };
              };
          };
      };
  }
}
