/**
 * This file was auto-generated by openapi-typescript (via scripts/gen-api.mjs).
 * Do not make direct changes to the file.
 */

export interface paths {
    "/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 재발급
         * @description Refresh Token으로 Access Token을 재발급한다.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 일반 로그인
         * @description 사용자 ID/비밀번호로 로그인하여 토큰을 발급한다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/erp-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ERP 로그인
         * @description ERP 연동 계정으로 로그인하여 토큰을 발급한다.
         */
        post: operations["erpLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RefreshTknRefreshTokenRequest: {
            /** @description 리프레시 토큰 */
            refreshToken: string;
        };
        AuthLoginRequest: {
            /**
             * @description 사용자 ID
             * @example hong.gildong
             */
            usrId: string;
            /**
             * Format: password
             * @description 비밀번호
             */
            usrPwd: string;
        };
        AuthErpLoginRequest: {
            /**
             * @description 사용자 ID
             * @example hong.gildong
             */
            usrId: string;
        };
        AuthResponse: {
            /**
             * @description 사용자 ID
             * @example hong.gildong
             */
            usrId?: string;
            /**
             * Format: password
             * @description 비밀번호
             */
            usrPwd?: string;
            /**
             * @description 사용자명
             * @example 홍길동
             */
            usrNm?: string;
            /**
             * @description 직위명
             * @example 대리
             */
            positDivName?: string;
            /**
             * @description 부서명
             * @example 채널개발팀
             */
            deptName?: string;
            /** @description 액세스 토큰 */
            accessToken?: string;
            /** @description 액세스 토큰 만료 일시 */
            accessTokenExpiresAt?: string;
            /** @description 리프레시 토큰 */
            refreshToken?: string;
            /** @description 리프레시 토큰 만료 일시 */
            refreshTokenExpiresAt?: string;
            /** @description 권한 목록 */
            roles?: string[];
        };
        ApiResponseAuthResponse: {
            success?: boolean;
            code?: string;
            msg?: string;
            requestId?: string;
            payload?: components["schemas"]["AuthResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTknRefreshTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        /** @description 성공 여부 */
                        success?: boolean;
                        /** @description 응답 코드 */
                        code?: string;
                        /** @description 응답 메시지 */
                        msg?: string;
                        /** @description 요청 추적 ID */
                        requestId?: string;
                        payload?: Record<string, never>;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        /** @description 성공 여부 */
                        success?: boolean;
                        /** @description 응답 코드 */
                        code?: string;
                        /** @description 응답 메시지 */
                        msg?: string;
                        /** @description 요청 추적 ID */
                        requestId?: string;
                        payload?: Record<string, never>;
                    };
                };
            };
        };
    };
    erpLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthErpLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        /** @description 성공 여부 */
                        success?: boolean;
                        /** @description 응답 코드 */
                        code?: string;
                        /** @description 응답 메시지 */
                        msg?: string;
                        /** @description 요청 추적 ID */
                        requestId?: string;
                        payload?: Record<string, never>;
                    };
                };
            };
        };
    };
}
