/**
 * This file was auto-generated by openapi-typescript (via scripts/gen-api.mjs).
 * Do not make direct changes to the file.
 */

export namespace system {
  export interface paths {
    '/reference-data/versions/latest': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /**
       * 기준정보 최신 버전 조회
       * @description data.refType이 ALL이면 전체 기준정보 최신 버전을 조회하고, 그 외에는 해당 기준정보 유형만 조회한다.
       */
      post: operations['getLatestReferenceDataVersions'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/menus/{menuId}/update': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 메뉴 수정 */
      post: operations['updateMenu'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/menus/{menuId}/actions/list': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 메뉴 기능 목록 조회 */
      post: operations['getMenuActions'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/menus/roles/{roleId}/save': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 역할별 메뉴 권한 저장 */
      post: operations['saveRoleMenus'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/menus/roles/{roleId}/list': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 역할별 메뉴 목록 조회 */
      post: operations['getMenusByRoleId'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/menus/list': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 메뉴 목록 조회 */
      post: operations['getMenus'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/menus/create': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 메뉴 등록 */
      post: operations['createMenu'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/common-codes/groups/{groupCd}/update': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 공통코드 그룹 수정 */
      post: operations['updateCommonCodeGroup'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/common-codes/groups/{groupCd}/codes/{code}/update': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 공통코드 수정 */
      post: operations['updateCommonCode'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/common-codes/groups/{groupCd}/codes/list': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 공통코드 목록 조회 */
      post: operations['getCommonCodes'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/common-codes/groups/{groupCd}/codes/create': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 공통코드 등록 */
      post: operations['createCommonCode'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/common-codes/groups/list': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 공통코드 그룹 목록 조회 */
      post: operations['getCommonCodeGroups'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/common-codes/groups/detail': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /**
       * 공통코드 그룹 상세 및 코드 목록 조회
       * @description data.groupCd가 ALL이면 전체 그룹과 하위 공통코드 목록을 조회하고, 그 외에는 해당 그룹만 조회한다.
       */
      post: operations['getCommonCodeGroupDetails'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/common-codes/groups/create': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 공통코드 그룹 등록 */
      post: operations['createCommonCodeGroup'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
  }
  export type webhooks = Record<string, never>;
  export interface components {
    schemas: {
      ApiRequestReferenceDataVersionReqDto: {
        pagination?: components['schemas']['PaginationReqDto'];
        filter?: components['schemas']['FilterReqDto'];
        sort?: components['schemas']['SortReqDto'];
        data?: components['schemas']['ReferenceDataVersionReqDto'];
      };
      FilterReqDto: {
        keyword?: string;
        searchType?: string;
        useYn?: string;
      };
      PaginationReqDto: {
        /** Format: int32 */
        page?: number;
        /** Format: int32 */
        size?: number;
        /** Format: int32 */
        offset?: number;
      };
      ReferenceDataVersionReqDto: {
        refType?: string;
      };
      SortReqDto: {
        sort?: string;
      };
      PaginationResDto: {
        /** Format: int32 */
        page?: number;
        /** Format: int32 */
        size?: number;
        /** Format: int64 */
        totalCount?: number;
        /** Format: int32 */
        totalPages?: number;
      };
      ApiRequestMenuReqDto: {
        pagination?: components['schemas']['PaginationReqDto'];
        filter?: components['schemas']['FilterReqDto'];
        sort?: components['schemas']['SortReqDto'];
        data?: components['schemas']['MenuReqDto'];
      };
      MenuReqDto: {
        /** Format: int64 */
        menuId?: number;
        /** Format: int64 */
        parentMenuId?: number;
        menuCd?: string;
        menuNm?: string;
        menuType?: string;
        path?: string;
        component?: string;
        icon?: string;
        /** Format: int32 */
        depth?: number;
        /** Format: int32 */
        sortSeq?: number;
        visibleYn?: string;
        useYn?: string;
        remark?: string;
        createdBy?: string;
      };
      ApiResponseVoid: {
        success?: boolean;
        code?: string;
        msg?: string;
        payload?: Record<string, never>;
        requestId?: string;
        pagination?: components['schemas']['PaginationResDto'];
      };
      ApiRequestRoleMenuSaveReqDto: {
        pagination?: components['schemas']['PaginationReqDto'];
        filter?: components['schemas']['FilterReqDto'];
        sort?: components['schemas']['SortReqDto'];
        data?: components['schemas']['RoleMenuSaveReqDto'];
      };
      RoleMenuSaveReqDto: {
        menuIds?: number[];
        createdBy?: string;
      };
      ApiRequestCommonCodeGroupReqDto: {
        pagination?: components['schemas']['PaginationReqDto'];
        filter?: components['schemas']['FilterReqDto'];
        sort?: components['schemas']['SortReqDto'];
        data?: components['schemas']['CommonCodeGroupReqDto'];
      };
      CommonCodeGroupReqDto: {
        groupCd?: string;
        groupNm?: string;
        groupDesc?: string;
        systemYn?: string;
        useYn?: string;
        /** Format: int32 */
        sortSeq?: number;
        createdBy?: string;
      };
      ApiRequestCommonCodeReqDto: {
        pagination?: components['schemas']['PaginationReqDto'];
        filter?: components['schemas']['FilterReqDto'];
        sort?: components['schemas']['SortReqDto'];
        data?: components['schemas']['CommonCodeReqDto'];
      };
      CommonCodeReqDto: {
        groupCd?: string;
        code?: string;
        codeNm?: string;
        codeDesc?: string;
        /** Format: int64 */
        parentCodeId?: number;
        /** Format: int32 */
        sortSeq?: number;
        useYn?: string;
        /** Format: date */
        validFrom?: string;
        /** Format: date */
        validTo?: string;
        extraData?: string;
        createdBy?: string;
      };
      MenuActionListResponse: {
        /**
         * Format: int64
         * @description 메뉴 기능 ID
         */
        actionId?: number;
        /**
         * Format: int64
         * @description 메뉴 ID
         */
        menuId?: number;
        /**
         * @description 기능 코드
         * @example READ
         */
        actionCd?: string;
        /**
         * @description 기능명
         * @example 조회
         */
        actionNm?: string;
        /**
         * @description HTTP 메서드
         * @example GET
         */
        httpMethod?: string;
        /**
         * @description API 패턴
         * @example /channel/backend/api/v1/system/menus/**
         */
        apiPattern?: string;
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /**
         * @description 생성자 ID
         * @example admin
         */
        createdBy?: string;
        /**
         * @description 수정자 ID
         * @example admin
         */
        updatedBy?: string;
        /**
         * Format: date-time
         * @description 생성 일시
         * @example 2026-01-01T09:00:00
         */
        createdAt?: string;
        /**
         * Format: date-time
         * @description 수정 일시
         * @example 2026-01-01T10:00:00
         */
        updatedAt?: string;
      };
      MenuListResponse: {
        /**
         * Format: int64
         * @description 메뉴 ID
         */
        menuId?: number;
        /**
         * Format: int64
         * @description 상위 메뉴 ID
         */
        parentMenuId?: number;
        /**
         * @description 메뉴 코드
         * @example DASHBOARD
         */
        menuCd?: string;
        /**
         * @description 메뉴명
         * @example 대시보드
         */
        menuNm?: string;
        /**
         * @description 메뉴 유형
         * @example MENU
         */
        menuType?: string;
        /**
         * @description 화면 경로
         * @example /dashboard
         */
        path?: string;
        /**
         * @description 프론트엔드 컴포넌트 경로
         * @example DashboardView
         */
        component?: string;
        /**
         * @description 아이콘명
         * @example LayoutDashboard
         */
        icon?: string;
        /**
         * Format: int32
         * @description 메뉴 깊이
         * @example 1
         */
        depth?: number;
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 노출 여부
         * @example Y
         * @enum {string}
         */
        visibleYn?: 'Y' | 'N';
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /** @description 비고 */
        remark?: string;
        /**
         * @description 생성자 ID
         * @example admin
         */
        createdBy?: string;
        /**
         * @description 수정자 ID
         * @example admin
         */
        updatedBy?: string;
        /**
         * Format: date-time
         * @description 생성 일시
         * @example 2026-01-01T09:00:00
         */
        createdAt?: string;
        /**
         * Format: date-time
         * @description 수정 일시
         * @example 2026-01-01T10:00:00
         */
        updatedAt?: string;
      };
      RoleMenuSaveSaveRequest: {
        /** @description 역할에 부여할 메뉴 ID 목록 */
        menuIds: number[];
        /**
         * @description 요청자 ID
         * @example admin
         */
        createdBy?: string;
      };
      MenuCreateRequest: {
        /**
         * Format: int64
         * @description 상위 메뉴 ID
         */
        parentMenuId?: number;
        /**
         * @description 메뉴 코드
         * @example DASHBOARD
         */
        menuCd: string;
        /**
         * @description 메뉴명
         * @example 대시보드
         */
        menuNm: string;
        /**
         * @description 메뉴 유형
         * @example MENU
         */
        menuType?: string;
        /**
         * @description 화면 경로
         * @example /dashboard
         */
        path?: string;
        /**
         * @description 프론트엔드 컴포넌트 경로
         * @example DashboardView
         */
        component?: string;
        /**
         * @description 아이콘명
         * @example LayoutDashboard
         */
        icon?: string;
        /**
         * Format: int32
         * @description 메뉴 깊이
         * @example 1
         */
        depth?: number;
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 노출 여부
         * @example Y
         * @enum {string}
         */
        visibleYn?: 'Y' | 'N';
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /** @description 비고 */
        remark?: string;
        /**
         * @description 요청자 ID
         * @example admin
         */
        createdBy?: string;
      };
      MenuUpdateRequest: {
        /**
         * Format: int64
         * @description 상위 메뉴 ID
         */
        parentMenuId?: number;
        /**
         * @description 메뉴명
         * @example 대시보드
         */
        menuNm: string;
        /**
         * @description 메뉴 유형
         * @example MENU
         */
        menuType?: string;
        /**
         * @description 화면 경로
         * @example /dashboard
         */
        path?: string;
        /**
         * @description 프론트엔드 컴포넌트 경로
         * @example DashboardView
         */
        component?: string;
        /**
         * @description 아이콘명
         * @example LayoutDashboard
         */
        icon?: string;
        /**
         * Format: int32
         * @description 메뉴 깊이
         * @example 1
         */
        depth?: number;
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 노출 여부
         * @example Y
         * @enum {string}
         */
        visibleYn?: 'Y' | 'N';
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /** @description 비고 */
        remark?: string;
        /**
         * @description 요청자 ID
         * @example admin
         */
        createdBy?: string;
      };
      ReferenceDataVersionLatestResponse: {
        /**
         * Format: int64
         * @description 기준정보 버전 ID
         * @example 1
         */
        versionId?: number;
        /**
         * @description 기준정보 유형
         * @example MENU
         */
        refType?: string;
        /**
         * @description 버전 번호
         * @example 0.0.1
         */
        versionNo?: string;
        /**
         * Format: date-time
         * @description 최종 변경 일시
         * @example 2026-06-25T16:04:14
         */
        lastChangedAt?: string;
        /**
         * @description 최종 변경자 ID
         * @example system
         */
        lastChangedBy?: string;
        /**
         * @description 비고
         * @example 메뉴 샘플 데이터 최초 버전
         */
        remark?: string;
      };
      ReferenceDataVersionLatestRequest: {
        /**
         * @description 기준정보 유형
         * @example ALL
         */
        refType: string;
      };
      CommonCodeListResponse: {
        /**
         * Format: int64
         * @description 공통코드 ID
         */
        codeId?: number;
        /**
         * Format: int64
         * @description 공통코드 그룹 ID
         */
        groupId?: number;
        /** @description 공통코드 그룹 코드 */
        groupCd?: string;
        /**
         * @description 공통코드
         * @example Y
         */
        code?: string;
        /**
         * @description 공통코드명
         * @example 사용
         */
        codeNm?: string;
        /** @description 공통코드 설명 */
        codeDesc?: string;
        /**
         * Format: int64
         * @description 상위 공통코드 ID
         */
        parentCodeId?: number;
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /**
         * Format: date
         * @description 유효 시작일
         * @example 2026-01-01
         */
        validFrom?: string;
        /**
         * Format: date
         * @description 유효 종료일
         * @example 2026-12-31
         */
        validTo?: string;
        /**
         * @description 추가 데이터 JSON 문자열
         * @example {}
         */
        extraData?: string;
        /**
         * @description 생성자 ID
         * @example admin
         */
        createdBy?: string;
        /**
         * @description 수정자 ID
         * @example admin
         */
        updatedBy?: string;
        /**
         * Format: date-time
         * @description 생성 일시
         * @example 2026-01-01T09:00:00
         */
        createdAt?: string;
        /**
         * Format: date-time
         * @description 수정 일시
         * @example 2026-01-01T10:00:00
         */
        updatedAt?: string;
      };
      CommonCodeDetailResponse: {
        /** @description 공통코드 그룹 코드 */
        groupCd?: string;
        /**
         * @description 공통코드
         * @example Y
         */
        code?: string;
        /**
         * @description 공통코드명
         * @example 사용
         */
        codeNm?: string;
        /** @description 공통코드 설명 */
        codeDesc?: string;
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
      };
      CommonCodeGroupCreateRequest: {
        /**
         * @description 공통코드 그룹 코드
         * @example ALL
         */
        groupCd: string;
        /**
         * @description 공통코드 그룹명
         * @example 사용 여부
         */
        groupNm: string;
        /** @description 공통코드 그룹 설명 */
        groupDesc?: string;
        /**
         * @description 시스템 코드 여부
         * @example N
         * @enum {string}
         */
        systemYn?: 'Y' | 'N';
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 요청자 ID
         * @example admin
         */
        createdBy?: string;
      };
      CommonCodeGroupUpdateRequest: {
        /**
         * @description 공통코드 그룹명
         * @example 사용 여부
         */
        groupNm: string;
        /** @description 공통코드 그룹 설명 */
        groupDesc?: string;
        /**
         * @description 시스템 코드 여부
         * @example N
         * @enum {string}
         */
        systemYn?: 'Y' | 'N';
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 요청자 ID
         * @example admin
         */
        createdBy?: string;
      };
      CommonCodeGroupDetailRequest: {
        /**
         * @description 공통코드 그룹 코드
         * @example ALL
         */
        groupCd: string;
      };
      CommonCodeGroupDetailDetailResponse: {
        /**
         * @description 공통코드 그룹 코드
         * @example USE_YN
         */
        groupCd?: string;
        /**
         * @description 공통코드 그룹명
         * @example 사용 여부
         */
        groupNm?: string;
        /** @description 공통코드 그룹 설명 */
        groupDesc?: string;
        /**
         * @description 시스템 코드 여부
         * @example Y
         * @enum {string}
         */
        systemYn?: 'Y' | 'N';
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /** @description 공통코드 목록 */
        codes?: string[];
      };
      CommonCodeCreateRequest: {
        /**
         * @description 공통코드
         * @example Y
         */
        code: string;
        /**
         * @description 공통코드명
         * @example 사용
         */
        codeNm: string;
        /** @description 공통코드 설명 */
        codeDesc?: string;
        /**
         * Format: int64
         * @description 상위 공통코드 ID
         */
        parentCodeId?: number;
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /**
         * Format: date
         * @description 유효 시작일
         * @example 2026-01-01
         */
        validFrom?: string;
        /**
         * Format: date
         * @description 유효 종료일
         * @example 2026-12-31
         */
        validTo?: string;
        /**
         * @description 추가 데이터 JSON 문자열
         * @example {}
         */
        extraData?: string;
        /**
         * @description 요청자 ID
         * @example admin
         */
        createdBy?: string;
      };
      CommonCodeUpdateRequest: {
        /**
         * @description 공통코드명
         * @example 사용
         */
        codeNm: string;
        /** @description 공통코드 설명 */
        codeDesc?: string;
        /**
         * Format: int64
         * @description 상위 공통코드 ID
         */
        parentCodeId?: number;
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /**
         * Format: date
         * @description 유효 시작일
         * @example 2026-01-01
         */
        validFrom?: string;
        /**
         * Format: date
         * @description 유효 종료일
         * @example 2026-12-31
         */
        validTo?: string;
        /**
         * @description 추가 데이터 JSON 문자열
         * @example {}
         */
        extraData?: string;
        /**
         * @description 요청자 ID
         * @example admin
         */
        createdBy?: string;
      };
      CommonCodeGroupListResponse: {
        /**
         * Format: int64
         * @description 공통코드 그룹 ID
         */
        groupId?: number;
        /**
         * @description 공통코드 그룹 코드
         * @example USE_YN
         */
        groupCd?: string;
        /**
         * @description 공통코드 그룹명
         * @example 사용 여부
         */
        groupNm?: string;
        /** @description 공통코드 그룹 설명 */
        groupDesc?: string;
        /**
         * @description 시스템 코드 여부
         * @example N
         * @enum {string}
         */
        systemYn?: 'Y' | 'N';
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 생성자 ID
         * @example admin
         */
        createdBy?: string;
        /**
         * @description 수정자 ID
         * @example admin
         */
        updatedBy?: string;
        /**
         * Format: date-time
         * @description 생성 일시
         * @example 2026-01-01T09:00:00
         */
        createdAt?: string;
        /**
         * Format: date-time
         * @description 수정 일시
         * @example 2026-01-01T10:00:00
         */
        updatedAt?: string;
      };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
  }
  export type $defs = Record<string, never>;
  export interface operations {
    getLatestReferenceDataVersions: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ApiRequestReferenceDataVersionReqDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: components['schemas']['ReferenceDataVersionLatestResponse'][];
            };
          };
        };
      };
    };
    updateMenu: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          menuId: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ApiRequestMenuReqDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: Record<string, never>;
            };
          };
        };
      };
    };
    getMenuActions: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          menuId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: components['schemas']['MenuActionListResponse'][];
            };
          };
        };
      };
    };
    saveRoleMenus: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          roleId: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ApiRequestRoleMenuSaveReqDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: Record<string, never>;
            };
          };
        };
      };
    };
    getMenusByRoleId: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          roleId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: components['schemas']['MenuListResponse'][];
            };
          };
        };
      };
    };
    getMenus: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: components['schemas']['MenuListResponse'][];
            };
          };
        };
      };
    };
    createMenu: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ApiRequestMenuReqDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: Record<string, never>;
            };
          };
        };
      };
    };
    updateCommonCodeGroup: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          groupCd: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ApiRequestCommonCodeGroupReqDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: Record<string, never>;
            };
          };
        };
      };
    };
    updateCommonCode: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          groupCd: string;
          code: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ApiRequestCommonCodeReqDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: Record<string, never>;
            };
          };
        };
      };
    };
    getCommonCodes: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          groupCd: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: components['schemas']['CommonCodeListResponse'][];
            };
          };
        };
      };
    };
    createCommonCode: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          groupCd: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ApiRequestCommonCodeReqDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: Record<string, never>;
            };
          };
        };
      };
    };
    getCommonCodeGroups: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: components['schemas']['CommonCodeGroupListResponse'][];
            };
          };
        };
      };
    };
    getCommonCodeGroupDetails: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ApiRequestCommonCodeGroupReqDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: components['schemas']['CommonCodeGroupDetailDetailResponse'][];
            };
          };
        };
      };
    };
    createCommonCodeGroup: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ApiRequestCommonCodeGroupReqDto'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: Record<string, never>;
            };
          };
        };
      };
    };
  }
}
