/**
 * This file was auto-generated by openapi-typescript (via scripts/gen-api.mjs).
 * Do not make direct changes to the file.
 */

export namespace system {
  export interface paths {
    '/reference-data/versions/latest': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /**
       * 기준정보 최신 버전 조회
       * @description data.refType이 ALL이면 전체 기준정보 최신 버전을 조회하고, 그 외에는 해당 기준정보 유형만 조회한다.
       */
      post: operations['getLatestReferenceDataVersions'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/menus/{menuId}/update': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 메뉴 수정 */
      post: operations['updateMenu'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/menus/{menuId}/detail': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 메뉴 상세 조회 */
      post: operations['getMenu'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/menus/{menuId}/delete': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 메뉴 삭제 */
      post: operations['deleteMenu'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/menus/{menuId}/actions/list': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 메뉴 기능 목록 조회 */
      post: operations['getMenuActions'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/menus/roles/{roleId}/save': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 역할별 메뉴 권한 저장 */
      post: operations['saveRoleMenus'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/menus/roles/{roleId}/list': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 역할별 메뉴 목록 조회 */
      post: operations['getMenusByRoleId'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/menus/list': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 메뉴 목록 조회 */
      post: operations['getMenus'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/menus/create': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 메뉴 등록 */
      post: operations['createMenu'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/common-codes/{groupCd}/replace': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 공통코드 그룹 및 코드 일괄 교체 */
      post: operations['replaceCommonCodes'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/common-codes/{groupCd}/detail': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 그룹별 공통코드 및 상세코드 조회 */
      post: operations['getCommonCodeGroupDetail'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/common-codes/{groupCd}/delete': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 공통코드 그룹 및 상세코드 통합 삭제 */
      post: operations['deleteCommonCodes'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/common-codes/list': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 전체 공통코드 그룹 및 상세코드 목록 조회 */
      post: operations['getCommonCodeGroupDetails'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/common-codes/groups/list': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 공통코드 그룹 목록 조회 */
      post: operations['getCommonCodeGroups'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
    '/common-codes/create': {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      get?: never;
      put?: never;
      /** 공통코드 그룹 및 상세코드 통합 등록 */
      post: operations['createCommonCodes'];
      delete?: never;
      options?: never;
      head?: never;
      patch?: never;
      trace?: never;
    };
  }
  export type webhooks = Record<string, never>;
  export interface components {
    schemas: {
      /**
       * @example {
       *       "actionId": 0,
       *       "menuId": 0,
       *       "actionCd": "READ",
       *       "actionNm": "조회",
       *       "httpMethod": "GET",
       *       "apiPattern": "/channel/backend/api/v1/system/menus/**",
       *       "sortSeq": "1",
       *       "useYn": "Y",
       *       "createdBy": "admin",
       *       "updatedBy": "admin",
       *       "createdAt": "2026-01-01T09:00:00+09:00",
       *       "updatedAt": "2026-01-01T10:00:00+09:00"
       *     }
       */
      MenuActionListResponse: {
        /**
         * Format: int64
         * @description 메뉴 기능 ID
         */
        actionId?: number;
        /**
         * Format: int64
         * @description 메뉴 ID
         */
        menuId?: number;
        /**
         * @description 기능 코드
         * @example READ
         */
        actionCd?: string;
        /**
         * @description 기능명
         * @example 조회
         */
        actionNm?: string;
        /**
         * @description HTTP 메서드
         * @example GET
         */
        httpMethod?: string;
        /**
         * @description API 패턴
         * @example /channel/backend/api/v1/system/menus/**
         */
        apiPattern?: string;
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /**
         * @description 생성자 ID
         * @example admin
         */
        createdBy?: string;
        /**
         * @description 수정자 ID
         * @example admin
         */
        updatedBy?: string;
        /**
         * Format: date-time
         * @description 생성 일시
         * @example 2026-01-01T09:00:00+09:00
         */
        createdAt?: string;
        /**
         * Format: date-time
         * @description 수정 일시
         * @example 2026-01-01T10:00:00+09:00
         */
        updatedAt?: string;
      };
      /**
       * @example {
       *       "menuId": 0,
       *       "parentMenuId": 0,
       *       "menuCd": "DASHBOARD",
       *       "menuNm": "대시보드",
       *       "menuType": "MENU",
       *       "path": "/dashboard",
       *       "component": "DashboardView",
       *       "icon": "LayoutDashboard",
       *       "depth": "1",
       *       "sortSeq": "1",
       *       "visibleYn": "Y",
       *       "useYn": "Y",
       *       "remark": "string",
       *       "createdBy": "admin",
       *       "updatedBy": "admin",
       *       "createdAt": "2026-01-01T09:00:00+09:00",
       *       "updatedAt": "2026-01-01T10:00:00+09:00"
       *     }
       */
      MenuListResponse: {
        /**
         * Format: int64
         * @description 메뉴 ID
         */
        menuId?: number;
        /**
         * Format: int64
         * @description 상위 메뉴 ID
         */
        parentMenuId?: number;
        /**
         * @description 메뉴 코드
         * @example DASHBOARD
         */
        menuCd?: string;
        /**
         * @description 메뉴명
         * @example 대시보드
         */
        menuNm?: string;
        /**
         * @description 메뉴 유형
         * @example MENU
         */
        menuType?: string;
        /**
         * @description 화면 경로
         * @example /dashboard
         */
        path?: string;
        /**
         * @description 프론트엔드 컴포넌트 경로
         * @example DashboardView
         */
        component?: string;
        /**
         * @description 아이콘명
         * @example LayoutDashboard
         */
        icon?: string;
        /**
         * Format: int32
         * @description 메뉴 깊이
         * @example 1
         */
        depth?: number;
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 노출 여부
         * @example Y
         * @enum {string}
         */
        visibleYn?: 'Y' | 'N';
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /** @description 비고 */
        remark?: string;
        /**
         * @description 생성자 ID
         * @example admin
         */
        createdBy?: string;
        /**
         * @description 수정자 ID
         * @example admin
         */
        updatedBy?: string;
        /**
         * Format: date-time
         * @description 생성 일시
         * @example 2026-01-01T09:00:00+09:00
         */
        createdAt?: string;
        /**
         * Format: date-time
         * @description 수정 일시
         * @example 2026-01-01T10:00:00+09:00
         */
        updatedAt?: string;
      };
      /**
       * @example {
       *       "data": {
       *         "menuIds": [
       *           0
       *         ]
       *       }
       *     }
       */
      RoleMenuSaveSaveRequest: {
        /**
         * @example {
         *       "menuIds": [
         *         0
         *       ]
         *     }
         */
        data: {
          /** @description 역할에 부여할 메뉴 ID 목록 */
          menuIds: number[];
        };
      };
      /**
       * @example {
       *       "menuId": 0,
       *       "parentMenuId": 0,
       *       "menuCd": "DASHBOARD",
       *       "menuNm": "대시보드",
       *       "menuType": "MENU",
       *       "path": "/dashboard",
       *       "component": "DashboardView",
       *       "icon": "LayoutDashboard",
       *       "depth": "1",
       *       "sortSeq": "1",
       *       "visibleYn": "Y",
       *       "useYn": "Y",
       *       "remark": "string",
       *       "createdBy": "admin",
       *       "updatedBy": "admin",
       *       "createdAt": "2026-01-01T09:00:00+09:00",
       *       "updatedAt": "2026-01-01T10:00:00+09:00"
       *     }
       */
      MenuDetailResponse: {
        /**
         * Format: int64
         * @description 메뉴 ID
         */
        menuId?: number;
        /**
         * Format: int64
         * @description 상위 메뉴 ID
         */
        parentMenuId?: number;
        /**
         * @description 메뉴 코드
         * @example DASHBOARD
         */
        menuCd?: string;
        /**
         * @description 메뉴명
         * @example 대시보드
         */
        menuNm?: string;
        /**
         * @description 메뉴 유형
         * @example MENU
         */
        menuType?: string;
        /**
         * @description 화면 경로
         * @example /dashboard
         */
        path?: string;
        /**
         * @description 프론트엔드 컴포넌트 경로
         * @example DashboardView
         */
        component?: string;
        /**
         * @description 아이콘명
         * @example LayoutDashboard
         */
        icon?: string;
        /**
         * Format: int32
         * @description 메뉴 깊이
         * @example 1
         */
        depth?: number;
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 노출 여부
         * @example Y
         * @enum {string}
         */
        visibleYn?: 'Y' | 'N';
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /** @description 비고 */
        remark?: string;
        /**
         * @description 생성자 ID
         * @example admin
         */
        createdBy?: string;
        /**
         * @description 수정자 ID
         * @example admin
         */
        updatedBy?: string;
        /**
         * Format: date-time
         * @description 생성 일시
         * @example 2026-01-01T09:00:00+09:00
         */
        createdAt?: string;
        /**
         * Format: date-time
         * @description 수정 일시
         * @example 2026-01-01T10:00:00+09:00
         */
        updatedAt?: string;
      };
      /**
       * @example {
       *       "data": {
       *         "parentMenuId": 0,
       *         "menuCd": "DASHBOARD",
       *         "menuNm": "대시보드",
       *         "menuType": "MENU",
       *         "path": "/dashboard",
       *         "component": "DashboardView",
       *         "icon": "LayoutDashboard",
       *         "depth": "1",
       *         "sortSeq": "1",
       *         "visibleYn": "Y",
       *         "useYn": "Y",
       *         "remark": "string"
       *       }
       *     }
       */
      MenuCreateRequest: {
        /**
         * @example {
         *       "parentMenuId": 0,
         *       "menuCd": "DASHBOARD",
         *       "menuNm": "대시보드",
         *       "menuType": "MENU",
         *       "path": "/dashboard",
         *       "component": "DashboardView",
         *       "icon": "LayoutDashboard",
         *       "depth": "1",
         *       "sortSeq": "1",
         *       "visibleYn": "Y",
         *       "useYn": "Y",
         *       "remark": "string"
         *     }
         */
        data: {
          /**
           * Format: int64
           * @description 상위 메뉴 ID
           */
          parentMenuId?: number;
          /**
           * @description 메뉴 코드
           * @example DASHBOARD
           */
          menuCd: string;
          /**
           * @description 메뉴명
           * @example 대시보드
           */
          menuNm: string;
          /**
           * @description 메뉴 유형
           * @example MENU
           */
          menuType?: string;
          /**
           * @description 화면 경로
           * @example /dashboard
           */
          path?: string;
          /**
           * @description 프론트엔드 컴포넌트 경로
           * @example DashboardView
           */
          component?: string;
          /**
           * @description 아이콘명
           * @example LayoutDashboard
           */
          icon?: string;
          /**
           * Format: int32
           * @description 메뉴 깊이
           * @example 1
           */
          depth?: number;
          /**
           * Format: int32
           * @description 정렬 순서
           * @example 1
           */
          sortSeq?: number;
          /**
           * @description 노출 여부
           * @example Y
           * @enum {string}
           */
          visibleYn?: 'Y' | 'N';
          /**
           * @description 사용 여부
           * @example Y
           * @enum {string}
           */
          useYn?: 'Y' | 'N';
          /** @description 비고 */
          remark?: string;
        };
      };
      /**
       * @example {
       *       "data": {
       *         "parentMenuId": 0,
       *         "menuNm": "대시보드",
       *         "menuType": "MENU",
       *         "path": "/dashboard",
       *         "component": "DashboardView",
       *         "icon": "LayoutDashboard",
       *         "depth": "1",
       *         "sortSeq": "1",
       *         "visibleYn": "Y",
       *         "useYn": "Y",
       *         "remark": "string"
       *       }
       *     }
       */
      MenuUpdateRequest: {
        /**
         * @example {
         *       "parentMenuId": 0,
         *       "menuNm": "대시보드",
         *       "menuType": "MENU",
         *       "path": "/dashboard",
         *       "component": "DashboardView",
         *       "icon": "LayoutDashboard",
         *       "depth": "1",
         *       "sortSeq": "1",
         *       "visibleYn": "Y",
         *       "useYn": "Y",
         *       "remark": "string"
         *     }
         */
        data: {
          /**
           * Format: int64
           * @description 상위 메뉴 ID
           */
          parentMenuId?: number;
          /**
           * @description 메뉴명
           * @example 대시보드
           */
          menuNm: string;
          /**
           * @description 메뉴 유형
           * @example MENU
           */
          menuType?: string;
          /**
           * @description 화면 경로
           * @example /dashboard
           */
          path?: string;
          /**
           * @description 프론트엔드 컴포넌트 경로
           * @example DashboardView
           */
          component?: string;
          /**
           * @description 아이콘명
           * @example LayoutDashboard
           */
          icon?: string;
          /**
           * Format: int32
           * @description 메뉴 깊이
           * @example 1
           */
          depth?: number;
          /**
           * Format: int32
           * @description 정렬 순서
           * @example 1
           */
          sortSeq?: number;
          /**
           * @description 노출 여부
           * @example Y
           * @enum {string}
           */
          visibleYn?: 'Y' | 'N';
          /**
           * @description 사용 여부
           * @example Y
           * @enum {string}
           */
          useYn?: 'Y' | 'N';
          /** @description 비고 */
          remark?: string;
        };
      };
      /**
       * @example {
       *       "versionId": "1",
       *       "refType": "MENU",
       *       "versionNo": "0.0.1",
       *       "lastChangedAt": "2026-06-25T16:04:14+09:00",
       *       "lastChangedBy": "system",
       *       "remark": "메뉴 샘플 데이터 최초 버전",
       *       "createdBy": "system",
       *       "updatedBy": "system",
       *       "createdAt": "2026-06-25T16:01:14+09:00",
       *       "updatedAt": "2026-06-25T16:01:14+09:00"
       *     }
       */
      ReferenceDataVersionLatestResponse: {
        /**
         * Format: int64
         * @description 기준정보 버전 ID
         * @example 1
         */
        versionId?: number;
        /**
         * @description 기준정보 유형
         * @example MENU
         */
        refType?: string;
        /**
         * @description 버전 번호
         * @example 0.0.1
         */
        versionNo?: string;
        /**
         * Format: date-time
         * @description 최종 변경 일시
         * @example 2026-06-25T16:04:14+09:00
         */
        lastChangedAt?: string;
        /**
         * @description 최종 변경자 ID
         * @example system
         */
        lastChangedBy?: string;
        /**
         * @description 비고
         * @example 메뉴 샘플 데이터 최초 버전
         */
        remark?: string;
        /**
         * @description 생성자 ID
         * @example system
         */
        createdBy?: string;
        /**
         * @description 수정자 ID
         * @example system
         */
        updatedBy?: string;
        /**
         * Format: date-time
         * @description 생성 일시
         * @example 2026-06-25T16:01:14+09:00
         */
        createdAt?: string;
        /**
         * Format: date-time
         * @description 수정 일시
         * @example 2026-06-25T16:01:14+09:00
         */
        updatedAt?: string;
      };
      /**
       * @example {
       *       "data": {
       *         "refType": "ALL"
       *       }
       *     }
       */
      ReferenceDataVersionLatestRequest: {
        /**
         * @example {
         *       "refType": "ALL"
         *     }
         */
        data: {
          /**
           * @description 기준정보 유형
           * @example ALL
           */
          refType: string;
        };
      };
      /**
       * @example {
       *       "codeId": 0,
       *       "groupId": 0,
       *       "groupCd": "string",
       *       "code": "Y",
       *       "codeNm": "사용",
       *       "codeDesc": "string",
       *       "parentCodeId": 0,
       *       "sortSeq": "1",
       *       "useYn": "Y",
       *       "validFrom": "2026-01-01",
       *       "validTo": "2026-12-31",
       *       "extraData": "{}",
       *       "createdBy": "admin",
       *       "updatedBy": "admin",
       *       "createdAt": "2026-01-01T09:00:00+09:00",
       *       "updatedAt": "2026-01-01T10:00:00+09:00"
       *     }
       */
      CommonCodeListResponse: {
        /**
         * Format: int64
         * @description 공통코드 ID
         */
        codeId?: number;
        /**
         * Format: int64
         * @description 공통코드 그룹 ID
         */
        groupId?: number;
        /** @description 공통코드 그룹 코드 */
        groupCd?: string;
        /**
         * @description 공통코드
         * @example Y
         */
        code?: string;
        /**
         * @description 공통코드명
         * @example 사용
         */
        codeNm?: string;
        /** @description 공통코드 설명 */
        codeDesc?: string;
        /**
         * Format: int64
         * @description 상위 공통코드 ID
         */
        parentCodeId?: number;
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /**
         * Format: date
         * @description 유효 시작일
         * @example 2026-01-01
         */
        validFrom?: string;
        /**
         * Format: date
         * @description 유효 종료일
         * @example 2026-12-31
         */
        validTo?: string;
        /**
         * @description 추가 데이터 JSON 문자열
         * @example {}
         */
        extraData?: string;
        /**
         * @description 생성자 ID
         * @example admin
         */
        createdBy?: string;
        /**
         * @description 수정자 ID
         * @example admin
         */
        updatedBy?: string;
        /**
         * Format: date-time
         * @description 생성 일시
         * @example 2026-01-01T09:00:00+09:00
         */
        createdAt?: string;
        /**
         * Format: date-time
         * @description 수정 일시
         * @example 2026-01-01T10:00:00+09:00
         */
        updatedAt?: string;
      };
      /**
       * @example {
       *       "groupCd": "string",
       *       "code": "Y",
       *       "codeNm": "사용",
       *       "codeDesc": "string",
       *       "sortSeq": "1",
       *       "useYn": "Y"
       *     }
       */
      CommonCodeDetailResponse: {
        /** @description 공통코드 그룹 코드 */
        groupCd?: string;
        /**
         * @description 공통코드
         * @example Y
         */
        code?: string;
        /**
         * @description 공통코드명
         * @example 사용
         */
        codeNm?: string;
        /** @description 공통코드 설명 */
        codeDesc?: string;
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
      };
      /**
       * @example {
       *       "groupCd": "USE_YN",
       *       "groupNm": "사용 여부",
       *       "groupDesc": "string",
       *       "systemYn": "Y",
       *       "useYn": "Y",
       *       "createdBy": "system",
       *       "updatedBy": "system",
       *       "createdAt": "2026-06-25T16:01:14+09:00",
       *       "updatedAt": "2026-06-25T16:01:14+09:00",
       *       "codes": [
       *         {
       *           "codeId": 0,
       *           "groupId": 0,
       *           "groupCd": "string",
       *           "code": "Y",
       *           "codeNm": "사용",
       *           "codeDesc": "string",
       *           "parentCodeId": 0,
       *           "sortSeq": "1",
       *           "useYn": "Y",
       *           "validFrom": "2026-01-01",
       *           "validTo": "2026-12-31",
       *           "extraData": "{}",
       *           "createdBy": "admin",
       *           "updatedBy": "admin",
       *           "createdAt": "2026-01-01T09:00:00+09:00",
       *           "updatedAt": "2026-01-01T10:00:00+09:00"
       *         }
       *       ]
       *     }
       */
      CommonCodeGroupDetailListResponse: {
        /**
         * @description 공통코드 그룹 코드
         * @example USE_YN
         */
        groupCd?: string;
        /**
         * @description 공통코드 그룹명
         * @example 사용 여부
         */
        groupNm?: string;
        /** @description 공통코드 그룹 설명 */
        groupDesc?: string;
        /**
         * @description 시스템 코드 여부
         * @example Y
         * @enum {string}
         */
        systemYn?: 'Y' | 'N';
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /**
         * @description 생성자 ID
         * @example system
         */
        createdBy?: string;
        /**
         * @description 수정자 ID
         * @example system
         */
        updatedBy?: string;
        /**
         * Format: date-time
         * @description 생성 일시
         * @example 2026-06-25T16:01:14+09:00
         */
        createdAt?: string;
        /**
         * Format: date-time
         * @description 수정 일시
         * @example 2026-06-25T16:01:14+09:00
         */
        updatedAt?: string;
        /** @description 공통코드 목록 */
        codes?: {
          /**
           * Format: int64
           * @description 공통코드 ID
           */
          codeId?: number;
          /**
           * Format: int64
           * @description 공통코드 그룹 ID
           */
          groupId?: number;
          /** @description 공통코드 그룹 코드 */
          groupCd?: string;
          /**
           * @description 공통코드
           * @example Y
           */
          code?: string;
          /**
           * @description 공통코드명
           * @example 사용
           */
          codeNm?: string;
          /** @description 공통코드 설명 */
          codeDesc?: string;
          /**
           * Format: int64
           * @description 상위 공통코드 ID
           */
          parentCodeId?: number;
          /**
           * Format: int32
           * @description 정렬 순서
           * @example 1
           */
          sortSeq?: number;
          /**
           * @description 사용 여부
           * @example Y
           * @enum {string}
           */
          useYn?: 'Y' | 'N';
          /**
           * Format: date
           * @description 유효 시작일
           * @example 2026-01-01
           */
          validFrom?: string;
          /**
           * Format: date
           * @description 유효 종료일
           * @example 2026-12-31
           */
          validTo?: string;
          /**
           * @description 추가 데이터 JSON 문자열
           * @example {}
           */
          extraData?: string;
          /**
           * @description 생성자 ID
           * @example admin
           */
          createdBy?: string;
          /**
           * @description 수정자 ID
           * @example admin
           */
          updatedBy?: string;
          /**
           * Format: date-time
           * @description 생성 일시
           * @example 2026-01-01T09:00:00+09:00
           */
          createdAt?: string;
          /**
           * Format: date-time
           * @description 수정 일시
           * @example 2026-01-01T10:00:00+09:00
           */
          updatedAt?: string;
        }[];
      };
      /**
       * @example {
       *       "groupCd": "USE_YN",
       *       "groupNm": "사용 여부",
       *       "groupDesc": "string",
       *       "systemYn": "Y",
       *       "useYn": "Y",
       *       "createdBy": "system",
       *       "updatedBy": "system",
       *       "createdAt": "2026-06-25T16:01:14+09:00",
       *       "updatedAt": "2026-06-25T16:01:14+09:00",
       *       "codes": [
       *         {
       *           "groupCd": "string",
       *           "code": "Y",
       *           "codeNm": "사용",
       *           "codeDesc": "string",
       *           "sortSeq": "1",
       *           "useYn": "Y"
       *         }
       *       ]
       *     }
       */
      CommonCodeGroupDetailDetailResponse: {
        /**
         * @description 공통코드 그룹 코드
         * @example USE_YN
         */
        groupCd?: string;
        /**
         * @description 공통코드 그룹명
         * @example 사용 여부
         */
        groupNm?: string;
        /** @description 공통코드 그룹 설명 */
        groupDesc?: string;
        /**
         * @description 시스템 코드 여부
         * @example Y
         * @enum {string}
         */
        systemYn?: 'Y' | 'N';
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /**
         * @description 생성자 ID
         * @example system
         */
        createdBy?: string;
        /**
         * @description 수정자 ID
         * @example system
         */
        updatedBy?: string;
        /**
         * Format: date-time
         * @description 생성 일시
         * @example 2026-06-25T16:01:14+09:00
         */
        createdAt?: string;
        /**
         * Format: date-time
         * @description 수정 일시
         * @example 2026-06-25T16:01:14+09:00
         */
        updatedAt?: string;
        /** @description 공통코드 목록 */
        codes?: {
          /** @description 공통코드 그룹 코드 */
          groupCd?: string;
          /**
           * @description 공통코드
           * @example Y
           */
          code?: string;
          /**
           * @description 공통코드명
           * @example 사용
           */
          codeNm?: string;
          /** @description 공통코드 설명 */
          codeDesc?: string;
          /**
           * Format: int32
           * @description 정렬 순서
           * @example 1
           */
          sortSeq?: number;
          /**
           * @description 사용 여부
           * @example Y
           * @enum {string}
           */
          useYn?: 'Y' | 'N';
        }[];
      };
      /**
       * @example {
       *       "data": {
       *         "groupCd": "USE_YN",
       *         "groupNm": "사용 여부",
       *         "groupDesc": "string",
       *         "systemYn": "N",
       *         "useYn": "Y",
       *         "sortSeq": "1",
       *         "codes": [
       *           {
       *             "code": "Y",
       *             "codeNm": "사용",
       *             "codeDesc": "string",
       *             "sortSeq": "1",
       *             "useYn": "Y",
       *             "validFrom": "2026-01-01",
       *             "validTo": "2026-12-31",
       *             "extraData": "{}"
       *           }
       *         ]
       *       }
       *     }
       */
      CommonCodeCreateCreateRequest: {
        /**
         * @example {
         *       "groupCd": "USE_YN",
         *       "groupNm": "사용 여부",
         *       "groupDesc": "string",
         *       "systemYn": "N",
         *       "useYn": "Y",
         *       "sortSeq": "1",
         *       "codes": [
         *         {
         *           "code": "Y",
         *           "codeNm": "사용",
         *           "codeDesc": "string",
         *           "sortSeq": "1",
         *           "useYn": "Y",
         *           "validFrom": "2026-01-01",
         *           "validTo": "2026-12-31",
         *           "extraData": "{}"
         *         }
         *       ]
         *     }
         */
        data: {
          /**
           * @description 공통코드 그룹 코드
           * @example USE_YN
           */
          groupCd: string;
          /**
           * @description 공통코드 그룹명
           * @example 사용 여부
           */
          groupNm: string;
          /** @description 공통코드 그룹 설명 */
          groupDesc?: string;
          /**
           * @description 시스템 코드 여부
           * @example N
           * @enum {string}
           */
          systemYn?: 'Y' | 'N';
          /**
           * @description 사용 여부
           * @example Y
           * @enum {string}
           */
          useYn?: 'Y' | 'N';
          /**
           * Format: int32
           * @description 정렬 순서
           * @example 1
           */
          sortSeq?: number;
          /** @description 등록할 상세코드 목록 */
          codes: {
            /**
             * @description 공통코드
             * @example Y
             */
            code: string;
            /**
             * @description 공통코드명
             * @example 사용
             */
            codeNm: string;
            /** @description 공통코드 설명 */
            codeDesc?: string;
            /**
             * Format: int32
             * @description 정렬 순서
             * @example 1
             */
            sortSeq?: number;
            /**
             * @description 사용 여부
             * @example Y
             * @enum {string}
             */
            useYn?: 'Y' | 'N';
            /**
             * Format: date
             * @description 유효 시작일
             * @example 2026-01-01
             */
            validFrom?: string;
            /**
             * Format: date
             * @description 유효 종료일
             * @example 2026-12-31
             */
            validTo?: string;
            /**
             * @description 추가 데이터 JSON 문자열
             * @example {}
             */
            extraData?: string;
          }[];
        };
      };
      /**
       * @example {
       *       "data": {
       *         "groupNm": "사용 여부",
       *         "groupDesc": "string",
       *         "systemYn": "N",
       *         "useYn": "Y",
       *         "sortSeq": "1",
       *         "codes": [
       *           {
       *             "code": "Y",
       *             "codeNm": "사용",
       *             "codeDesc": "string",
       *             "sortSeq": "1",
       *             "useYn": "Y",
       *             "validFrom": "2026-01-01",
       *             "validTo": "2026-12-31",
       *             "extraData": "{}"
       *           }
       *         ]
       *       }
       *     }
       */
      CommonCodeReplaceReplaceRequest: {
        /**
         * @example {
         *       "groupNm": "사용 여부",
         *       "groupDesc": "string",
         *       "systemYn": "N",
         *       "useYn": "Y",
         *       "sortSeq": "1",
         *       "codes": [
         *         {
         *           "code": "Y",
         *           "codeNm": "사용",
         *           "codeDesc": "string",
         *           "sortSeq": "1",
         *           "useYn": "Y",
         *           "validFrom": "2026-01-01",
         *           "validTo": "2026-12-31",
         *           "extraData": "{}"
         *         }
         *       ]
         *     }
         */
        data: {
          /**
           * @description 공통코드 그룹명
           * @example 사용 여부
           */
          groupNm: string;
          /** @description 공통코드 그룹 설명 */
          groupDesc?: string;
          /**
           * @description 시스템 코드 여부
           * @example N
           * @enum {string}
           */
          systemYn?: 'Y' | 'N';
          /**
           * @description 사용 여부
           * @example Y
           * @enum {string}
           */
          useYn?: 'Y' | 'N';
          /**
           * Format: int32
           * @description 정렬 순서
           * @example 1
           */
          sortSeq?: number;
          /** @description 교체할 상세코드 전체 목록 */
          codes: {
            /**
             * @description 공통코드
             * @example Y
             */
            code: string;
            /**
             * @description 공통코드명
             * @example 사용
             */
            codeNm: string;
            /** @description 공통코드 설명 */
            codeDesc?: string;
            /**
             * Format: int32
             * @description 정렬 순서
             * @example 1
             */
            sortSeq?: number;
            /**
             * @description 사용 여부
             * @example Y
             * @enum {string}
             */
            useYn?: 'Y' | 'N';
            /**
             * Format: date
             * @description 유효 시작일
             * @example 2026-01-01
             */
            validFrom?: string;
            /**
             * Format: date
             * @description 유효 종료일
             * @example 2026-12-31
             */
            validTo?: string;
            /**
             * @description 추가 데이터 JSON 문자열
             * @example {}
             */
            extraData?: string;
          }[];
        };
      };
      /**
       * @example {
       *       "data": {
       *         "code": "Y",
       *         "codeNm": "사용",
       *         "codeDesc": "string",
       *         "sortSeq": "1",
       *         "useYn": "Y",
       *         "validFrom": "2026-01-01",
       *         "validTo": "2026-12-31",
       *         "extraData": "{}"
       *       }
       *     }
       */
      CommonCodeCreateRequest: {
        /**
         * @example {
         *       "code": "Y",
         *       "codeNm": "사용",
         *       "codeDesc": "string",
         *       "sortSeq": "1",
         *       "useYn": "Y",
         *       "validFrom": "2026-01-01",
         *       "validTo": "2026-12-31",
         *       "extraData": "{}"
         *     }
         */
        data: {
          /**
           * @description 공통코드
           * @example Y
           */
          code: string;
          /**
           * @description 공통코드명
           * @example 사용
           */
          codeNm: string;
          /** @description 공통코드 설명 */
          codeDesc?: string;
          /**
           * Format: int32
           * @description 정렬 순서
           * @example 1
           */
          sortSeq?: number;
          /**
           * @description 사용 여부
           * @example Y
           * @enum {string}
           */
          useYn?: 'Y' | 'N';
          /**
           * Format: date
           * @description 유효 시작일
           * @example 2026-01-01
           */
          validFrom?: string;
          /**
           * Format: date
           * @description 유효 종료일
           * @example 2026-12-31
           */
          validTo?: string;
          /**
           * @description 추가 데이터 JSON 문자열
           * @example {}
           */
          extraData?: string;
        };
      };
      /**
       * @example {
       *       "data": {
       *         "code": "Y",
       *         "codeNm": "사용",
       *         "codeDesc": "string",
       *         "sortSeq": "1",
       *         "useYn": "Y",
       *         "validFrom": "2026-01-01",
       *         "validTo": "2026-12-31",
       *         "extraData": "{}"
       *       }
       *     }
       */
      CommonCodeReplaceRequest: {
        /**
         * @example {
         *       "code": "Y",
         *       "codeNm": "사용",
         *       "codeDesc": "string",
         *       "sortSeq": "1",
         *       "useYn": "Y",
         *       "validFrom": "2026-01-01",
         *       "validTo": "2026-12-31",
         *       "extraData": "{}"
         *     }
         */
        data: {
          /**
           * @description 공통코드
           * @example Y
           */
          code: string;
          /**
           * @description 공통코드명
           * @example 사용
           */
          codeNm: string;
          /** @description 공통코드 설명 */
          codeDesc?: string;
          /**
           * Format: int32
           * @description 정렬 순서
           * @example 1
           */
          sortSeq?: number;
          /**
           * @description 사용 여부
           * @example Y
           * @enum {string}
           */
          useYn?: 'Y' | 'N';
          /**
           * Format: date
           * @description 유효 시작일
           * @example 2026-01-01
           */
          validFrom?: string;
          /**
           * Format: date
           * @description 유효 종료일
           * @example 2026-12-31
           */
          validTo?: string;
          /**
           * @description 추가 데이터 JSON 문자열
           * @example {}
           */
          extraData?: string;
        };
      };
      /**
       * @example {
       *       "groupId": 0,
       *       "groupCd": "USE_YN",
       *       "groupNm": "사용 여부",
       *       "groupDesc": "string",
       *       "systemYn": "N",
       *       "useYn": "Y",
       *       "sortSeq": "1",
       *       "createdBy": "admin",
       *       "updatedBy": "admin",
       *       "createdAt": "2026-01-01T09:00:00+09:00",
       *       "updatedAt": "2026-01-01T10:00:00+09:00"
       *     }
       */
      CommonCodeGroupListResponse: {
        /**
         * Format: int64
         * @description 공통코드 그룹 ID
         */
        groupId?: number;
        /**
         * @description 공통코드 그룹 코드
         * @example USE_YN
         */
        groupCd?: string;
        /**
         * @description 공통코드 그룹명
         * @example 사용 여부
         */
        groupNm?: string;
        /** @description 공통코드 그룹 설명 */
        groupDesc?: string;
        /**
         * @description 시스템 코드 여부
         * @example N
         * @enum {string}
         */
        systemYn?: 'Y' | 'N';
        /**
         * @description 사용 여부
         * @example Y
         * @enum {string}
         */
        useYn?: 'Y' | 'N';
        /**
         * Format: int32
         * @description 정렬 순서
         * @example 1
         */
        sortSeq?: number;
        /**
         * @description 생성자 ID
         * @example admin
         */
        createdBy?: string;
        /**
         * @description 수정자 ID
         * @example admin
         */
        updatedBy?: string;
        /**
         * Format: date-time
         * @description 생성 일시
         * @example 2026-01-01T09:00:00+09:00
         */
        createdAt?: string;
        /**
         * Format: date-time
         * @description 수정 일시
         * @example 2026-01-01T10:00:00+09:00
         */
        updatedAt?: string;
      };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
  }
  export type $defs = Record<string, never>;
  export interface operations {
    getLatestReferenceDataVersions: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          /**
           * @example {
           *       "data": {
           *         "refType": "ALL"
           *       }
           *     }
           */
          'application/json': components['schemas']['ReferenceDataVersionLatestRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: components['schemas']['ReferenceDataVersionLatestResponse'][];
            };
          };
        };
      };
    };
    updateMenu: {
      parameters: {
        query?: never;
        header: {
          'X-Auth-User': string;
        };
        path: {
          menuId: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          /**
           * @example {
           *       "data": {
           *         "parentMenuId": 0,
           *         "menuNm": "대시보드",
           *         "menuType": "MENU",
           *         "path": "/dashboard",
           *         "component": "DashboardView",
           *         "icon": "LayoutDashboard",
           *         "depth": "1",
           *         "sortSeq": "1",
           *         "visibleYn": "Y",
           *         "useYn": "Y",
           *         "remark": "string"
           *       }
           *     }
           */
          'application/json': components['schemas']['MenuUpdateRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: Record<string, never>;
            };
          };
        };
      };
    };
    getMenu: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          menuId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: components['schemas']['MenuDetailResponse'];
            };
          };
        };
      };
    };
    deleteMenu: {
      parameters: {
        query?: never;
        header: {
          'X-Auth-User': string;
        };
        path: {
          menuId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: Record<string, never>;
            };
          };
        };
      };
    };
    getMenuActions: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          menuId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: components['schemas']['MenuActionListResponse'][];
            };
          };
        };
      };
    };
    saveRoleMenus: {
      parameters: {
        query?: never;
        header: {
          'X-Auth-User': string;
        };
        path: {
          roleId: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          /**
           * @example {
           *       "data": {
           *         "menuIds": "string"
           *       }
           *     }
           */
          'application/json': components['schemas']['RoleMenuSaveSaveRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: Record<string, never>;
            };
          };
        };
      };
    };
    getMenusByRoleId: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          roleId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: components['schemas']['MenuListResponse'][];
            };
          };
        };
      };
    };
    getMenus: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: components['schemas']['MenuListResponse'][];
            };
          };
        };
      };
    };
    createMenu: {
      parameters: {
        query?: never;
        header: {
          'X-Auth-User': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          /**
           * @example {
           *       "data": {
           *         "parentMenuId": 0,
           *         "menuCd": "DASHBOARD",
           *         "menuNm": "대시보드",
           *         "menuType": "MENU",
           *         "path": "/dashboard",
           *         "component": "DashboardView",
           *         "icon": "LayoutDashboard",
           *         "depth": "1",
           *         "sortSeq": "1",
           *         "visibleYn": "Y",
           *         "useYn": "Y",
           *         "remark": "string"
           *       }
           *     }
           */
          'application/json': components['schemas']['MenuCreateRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: Record<string, never>;
            };
          };
        };
      };
    };
    replaceCommonCodes: {
      parameters: {
        query?: never;
        header: {
          'X-Auth-User': string;
        };
        path: {
          groupCd: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          /**
           * @example {
           *       "data": {
           *         "groupNm": "사용 여부",
           *         "groupDesc": "string",
           *         "systemYn": "N",
           *         "useYn": "Y",
           *         "sortSeq": "1",
           *         "codes": "string"
           *       }
           *     }
           */
          'application/json': components['schemas']['CommonCodeReplaceReplaceRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: Record<string, never>;
            };
          };
        };
      };
    };
    getCommonCodeGroupDetail: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          groupCd: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: components['schemas']['CommonCodeGroupDetailDetailResponse'][];
            };
          };
        };
      };
    };
    deleteCommonCodes: {
      parameters: {
        query?: never;
        header: {
          'X-Auth-User': string;
        };
        path: {
          groupCd: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: Record<string, never>;
            };
          };
        };
      };
    };
    getCommonCodeGroupDetails: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: components['schemas']['CommonCodeGroupDetailListResponse'][];
            };
          };
        };
      };
    };
    getCommonCodeGroups: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: components['schemas']['CommonCodeGroupListResponse'][];
            };
          };
        };
      };
    };
    createCommonCodes: {
      parameters: {
        query?: never;
        header: {
          'X-Auth-User': string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          /**
           * @example {
           *       "data": {
           *         "groupCd": "USE_YN",
           *         "groupNm": "사용 여부",
           *         "groupDesc": "string",
           *         "systemYn": "N",
           *         "useYn": "Y",
           *         "sortSeq": "1",
           *         "codes": "string"
           *       }
           *     }
           */
          'application/json': components['schemas']['CommonCodeCreateCreateRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            '*/*': {
              /** @description 성공 여부 */
              success?: boolean;
              /** @description 응답 코드 */
              code?: string;
              /** @description 응답 메시지 */
              msg?: string;
              /** @description 요청 추적 ID */
              requestId?: string;
              payload?: Record<string, never>;
            };
          };
        };
      };
    };
  }
}
