/**
 * Generate OpenAPI TypeScript definitions for multiple backend services.
 *
 * Default services:
 *   - auth:    http://192.168.110.217:18081/auth-svc/v3/api-docs
 *   - product: http://192.168.110.217:18081/product-svc/v3/api-docs
 *   - system:  http://192.168.110.217:18081/system-svc/v3/api-docs
 *
 * Override with API_DOCS_URLS when needed:
 *   API_DOCS_URLS='auth=http://.../auth-svc/v3/api-docs,product=http://.../product-svc/v3/api-docs,system=http://.../system-svc/v3/api-docs'
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { basename } from 'node:path';
import { pathToFileURL } from 'node:url';

import openapiTS, { astToString } from 'openapi-typescript';

const OUT_DIR = new URL('../packages/shared/src/shared/api/', import.meta.url);

const DEFAULT_SERVICES = [
  { name: 'auth', url: 'http://192.168.110.217:18081/auth-svc/v3/api-docs' },
  { name: 'product', url: 'http://192.168.110.217:18081/product-svc/v3/api-docs' },
  { name: 'system', url: 'http://192.168.110.217:18081/system-svc/v3/api-docs' },
];

const BANNER = `/**
 * This file was auto-generated by openapi-typescript (via scripts/gen-api.mjs).
 * Do not make direct changes to the file.
 */

`;

const INDEX_BANNER = `/**
 * This file was auto-generated by scripts/gen-api.mjs.
 * Do not make direct changes to the file.
 */

`;

const SERVICE_NAME_RE = /^[A-Za-z_$][\w$]*$/;

const clone = (value) => JSON.parse(JSON.stringify(value));

const indent = (text) =>
  text
    .trimEnd()
    .split('\n')
    .map((line) => (line ? `  ${line}` : line))
    .join('\n');

const parseServiceList = (raw) => {
  if (!raw?.trim()) return DEFAULT_SERVICES;

  const parsed = raw
    .split(',')
    .map((entry) => entry.trim())
    .filter(Boolean)
    .map((entry) => {
      const separator = entry.indexOf('=');
      if (separator === -1) {
        throw new Error(`Invalid API_DOCS_URLS entry: ${entry}. Expected name=url.`);
      }
      return {
        name: entry.slice(0, separator).trim(),
        url: entry.slice(separator + 1).trim(),
      };
    });

  if (parsed.length === 0) return DEFAULT_SERVICES;
  return parsed;
};

const assertValidServiceName = (name) => {
  if (!SERVICE_NAME_RE.test(name)) {
    throw new Error(`Invalid service name "${name}". Use a valid TypeScript identifier.`);
  }
};

const patchMissingApiResponseSchemas = (doc, serviceName) => {
  doc.components ??= {};
  doc.components.schemas ??= {};
  const schemas = doc.components.schemas;

  const used = new Set();
  for (const match of JSON.stringify(doc).matchAll(/#\/components\/schemas\/([^"/]+)/g)) {
    used.add(match[1]);
  }

  let patched = 0;
  for (const name of used) {
    if (schemas[name]) continue;

    const payloadName = name.replace(/^ApiResponse/, '');
    const payload = schemas[payloadName]
      ? { $ref: `#/components/schemas/${payloadName}` }
      : { type: 'object', additionalProperties: true };

    schemas[name] = {
      type: 'object',
      properties: {
        success: { type: 'boolean' },
        code: { type: 'string' },
        msg: { type: 'string' },
        requestId: { type: 'string' },
        payload,
      },
    };
    patched++;
    console.warn(`[gen-api:${serviceName}] patched missing schema: ${name}`);
  }

  return patched;
};

const toServiceSchema = async ({ name, doc }) => {
  assertValidServiceName(name);

  const patchedDoc = clone(doc);
  const patched = patchMissingApiResponseSchemas(patchedDoc, name);
  const typeText = astToString(await openapiTS(patchedDoc));

  return {
    path: `${name}.schema.d.ts`,
    content: `${BANNER}export namespace ${name} {\n${indent(typeText)}\n}\n`,
    patched,
  };
};

const toIndex = (services) => ({
  path: 'index.ts',
  content: `${INDEX_BANNER}${services
    .map(({ name }) => `export type { ${name} } from './${name}.schema';`)
    .join('\n')}\n`,
});

const toRoutes = (services) => ({
  path: 'routes.json',
  content: `${JSON.stringify(
    {
      generatedBy: 'scripts/gen-api.mjs',
      services: services.map(({ name, doc }) => ({
        name,
        serverUrl: doc.servers?.[0]?.url ?? null,
      })),
    },
    null,
    2,
  )}\n`,
});

export const buildServiceOutputs = async (services) => {
  const files = [];
  let patched = 0;

  for (const service of services) {
    const output = await toServiceSchema(service);
    files.push({ path: output.path, content: output.content });
    patched += output.patched;
  }

  files.push(toRoutes(services));
  files.push(toIndex(services));
  return { files, patched };
};

const fetchServiceDocs = async (services) => {
  const docs = [];

  for (const service of services) {
    assertValidServiceName(service.name);
    const res = await fetch(service.url);
    if (!res.ok) {
      throw new Error(`OpenAPI request failed: ${res.status} ${res.statusText} (${service.url})`);
    }
    docs.push({ name: service.name, doc: await res.json() });
  }

  return docs;
};

export const generateApiSchemas = async ({
  services = parseServiceList(process.env.API_DOCS_URLS),
  outDir = OUT_DIR,
} = {}) => {
  const serviceDocs = await fetchServiceDocs(services);
  const outputs = await buildServiceOutputs(serviceDocs);

  await mkdir(outDir, { recursive: true });
  await Promise.all(
    outputs.files.map((file) => writeFile(new URL(file.path, outDir), file.content, 'utf8')),
  );

  return outputs;
};

const isDirectRun =
  process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;

if (isDirectRun) {
  const outputs = await generateApiSchemas();
  for (const file of outputs.files) {
    console.log(`[gen-api] generated ${basename(file.path)}`);
  }
  if (outputs.patched > 0) {
    console.warn(`[gen-api] patched ${outputs.patched} missing ApiResponse schema(s)`);
  }
}
