/**
 * OpenAPI → TS 타입 생성 (openapi-typescript 래퍼)
 *
 * 백엔드 springdoc이 제네릭 envelope 래퍼(`ApiResponse<T>` → `ApiResponseXxx`)의
 * 스키마를 `components.schemas`에 등록하지 못해 깨진 `$ref`를 내려주는 문제가 있다.
 * 이 스크립트는 누락된 `ApiResponse*` 스키마를 envelope 형태로 자동 보강한 뒤 생성한다.
 *
 * → 백엔드가 스펙을 고치면(누락 ref가 사라지면) 보강 로직은 자동으로 no-op이 되므로,
 *   수정 후에도 이 스크립트를 그대로 쓰면 된다.
 *
 * 스펙 URL은 환경변수 API_DOCS_URL로 덮어쓸 수 있다.
 */
import { writeFile } from 'node:fs/promises';
import openapiTS, { astToString } from 'openapi-typescript';

const API_DOCS_URL =
  process.env.API_DOCS_URL ?? 'http://192.168.11.197:18081/auth-svc/v3/api-docs';
const OUT = new URL('../packages/shared/src/shared/api/schema.d.ts', import.meta.url);

const BANNER = `/**
 * This file was auto-generated by openapi-typescript (via scripts/gen-api.mjs).
 * Do not make direct changes to the file.
 */

`;

const res = await fetch(API_DOCS_URL);
if (!res.ok) throw new Error(`스펙 요청 실패: ${res.status} ${res.statusText} (${API_DOCS_URL})`);
const doc = await res.json();

// --- 누락된 ApiResponse* envelope 스키마 보강 ---
doc.components ??= {};
const components = doc.components;
components.schemas ??= {};
const schemas = components.schemas;

const used = new Set();
for (const m of JSON.stringify(doc).matchAll(/#\/components\/schemas\/([^"/]+)/g)) {
  used.add(m[1]);
}

let patched = 0;
for (const name of used) {
  if (schemas[name]) continue; // 이미 정의됨 → 건너뜀 (백엔드 수정 시 여기로 빠짐)
  // ApiResponseXxx → payload 타입 Xxx. 정의돼 있으면 참조, 없으면 generic object.
  const payloadName = name.replace(/^ApiResponse/, '');
  const payload = schemas[payloadName]
    ? { $ref: `#/components/schemas/${payloadName}` }
    : { type: 'object', additionalProperties: true };
  schemas[name] = {
    type: 'object',
    properties: {
      success: { type: 'boolean' },
      code: { type: 'string' },
      msg: { type: 'string' },
      requestId: { type: 'string' },
      payload,
    },
  };
  patched++;
  console.warn(`[gen-api] 누락 스키마 보강: ${name} (payload=${payloadName})`);
}
if (patched > 0) {
  console.warn(`[gen-api] ⚠ ${patched}개 스키마를 임시 보강함 — 백엔드 스펙 수정 시 자동 해제됩니다.`);
}

const ast = await openapiTS(doc);
await writeFile(OUT, BANNER + astToString(ast), 'utf8');
console.log('[gen-api] ✔ schema.d.ts 생성 완료');
